drop table if exists users cascade;
drop table if exists cards cascade;
drop table if exists contact_info cascade;
drop table if exists bills cascade;
drop table if exists users_cards cascade;

create table if not exists bills
(
    id        int8 generated by default as identity,
    header    varchar(255),
    paid_date timestamp,
    total     float4 not null,
    card_id   int8 not null,
    primary key (id)
);

create table if not exists cards
(
    id       int8 generated by default as identity,
    balance  float4 not null,
    currency varchar(255) not null,
    primary key (id)
);

create table if not exists contact_info
(
    id       int8 generated by default as identity,
    email    varchar(255) null,
    phone    varchar(255) null,
    telegram varchar(255) null,
    primary key (id)
);

create table if not exists users
(
    id              int8 generated by default as identity,
    name            varchar(255) not null unique,
    role            varchar(255),
    contact_info_id int8,
    primary key (id)
);

create table if not exists users_cards
(
    user_id int8 not null,
    card_id int8 not null
);

alter table if exists bills
    add constraint bills_cards_fk
        foreign key (card_id)
            references cards;

alter table if exists users
    add constraint users_contact_info_fk
        foreign key (contact_info_id)
            references contact_info;

alter table if exists users_cards
    add constraint users_cards_cards_fk
        foreign key (card_id)
            references cards;

alter table if exists users_cards
    add constraint users_cards_users_fk
        foreign key (user_id)
            references users;